// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferenceRouteSpec {
    #[prost(string, tag = "1")]
    pub routing_hint: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub base_url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub api_key: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub enabled: bool,
}
/// Inference route model stored by Navigator.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferenceRoute {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub spec: ::core::option::Option<InferenceRouteSpec>,
    /// Human-friendly name, unique per object type. Auto-generated if not provided.
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateInferenceRouteRequest {
    #[prost(message, optional, tag = "1")]
    pub route: ::core::option::Option<InferenceRouteSpec>,
    /// Optional name. If empty, a random 6-char name is generated.
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateInferenceRouteRequest {
    /// Route name (canonical lookup key).
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub route: ::core::option::Option<InferenceRouteSpec>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteInferenceRouteRequest {
    /// Route name (canonical lookup key).
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteInferenceRouteResponse {
    #[prost(bool, tag = "1")]
    pub deleted: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListInferenceRoutesRequest {
    #[prost(uint32, tag = "1")]
    pub limit: u32,
    #[prost(uint32, tag = "2")]
    pub offset: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListInferenceRoutesResponse {
    #[prost(message, repeated, tag = "1")]
    pub routes: ::prost::alloc::vec::Vec<InferenceRoute>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferenceRouteResponse {
    #[prost(message, optional, tag = "1")]
    pub route: ::core::option::Option<InferenceRoute>,
}
/// Completion request.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompletionRequest {
    /// Routing hint tells the router what kind of inference to use (e.g. "frontier", "local").
    /// The router resolves this to a specific model and backend.
    #[prost(string, tag = "1")]
    pub routing_hint: ::prost::alloc::string::String,
    /// Chat messages for the completion.
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<ChatMessage>,
    /// Sampling temperature.
    #[prost(float, optional, tag = "3")]
    pub temperature: ::core::option::Option<f32>,
    /// Maximum number of tokens to generate.
    #[prost(int32, optional, tag = "4")]
    pub max_tokens: ::core::option::Option<i32>,
    /// Nucleus sampling parameter.
    #[prost(float, optional, tag = "5")]
    pub top_p: ::core::option::Option<f32>,
}
/// A single chat message.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatMessage {
    /// Message role (e.g. "system", "user", "assistant").
    #[prost(string, tag = "1")]
    pub role: ::prost::alloc::string::String,
    /// Message content.
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    /// Optional model reasoning content when provided by upstream.
    #[prost(string, optional, tag = "3")]
    pub reasoning_content: ::core::option::Option<::prost::alloc::string::String>,
}
/// Completion response.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompletionResponse {
    /// Unique completion ID.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// The actual model that served the request (resolved by router).
    #[prost(string, tag = "2")]
    pub model: ::prost::alloc::string::String,
    /// Creation timestamp (unix seconds).
    #[prost(int64, tag = "3")]
    pub created: i64,
    /// Completion choices.
    #[prost(message, repeated, tag = "4")]
    pub choices: ::prost::alloc::vec::Vec<CompletionChoice>,
    /// Token usage statistics.
    #[prost(message, optional, tag = "5")]
    pub usage: ::core::option::Option<CompletionUsage>,
}
/// A single completion choice.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompletionChoice {
    /// Choice index.
    #[prost(int32, tag = "1")]
    pub index: i32,
    /// The generated message.
    #[prost(message, optional, tag = "2")]
    pub message: ::core::option::Option<ChatMessage>,
    /// Reason the generation stopped (e.g. "stop", "length").
    #[prost(string, tag = "3")]
    pub finish_reason: ::prost::alloc::string::String,
}
/// Token usage statistics.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CompletionUsage {
    /// Number of tokens in the prompt.
    #[prost(int32, tag = "1")]
    pub prompt_tokens: i32,
    /// Number of tokens in the completion.
    #[prost(int32, tag = "2")]
    pub completion_tokens: i32,
    /// Total tokens used.
    #[prost(int32, tag = "3")]
    pub total_tokens: i32,
}
/// Generated client implementations.
pub mod inference_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Inference service provides LLM completion capabilities.
    #[derive(Debug, Clone)]
    pub struct InferenceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl InferenceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> InferenceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InferenceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            InferenceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Send a completion request routed by the server's inference router.
        pub async fn completion(
            &mut self,
            request: impl tonic::IntoRequest<super::CompletionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CompletionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/navigator.inference.v1.Inference/Completion",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("navigator.inference.v1.Inference", "Completion"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Create a new inference route.
        pub async fn create_inference_route(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateInferenceRouteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InferenceRouteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/navigator.inference.v1.Inference/CreateInferenceRoute",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "navigator.inference.v1.Inference",
                        "CreateInferenceRoute",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Update an existing inference route.
        pub async fn update_inference_route(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateInferenceRouteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InferenceRouteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/navigator.inference.v1.Inference/UpdateInferenceRoute",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "navigator.inference.v1.Inference",
                        "UpdateInferenceRoute",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Delete an inference route.
        pub async fn delete_inference_route(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteInferenceRouteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteInferenceRouteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/navigator.inference.v1.Inference/DeleteInferenceRoute",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "navigator.inference.v1.Inference",
                        "DeleteInferenceRoute",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// List inference routes.
        pub async fn list_inference_routes(
            &mut self,
            request: impl tonic::IntoRequest<super::ListInferenceRoutesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListInferenceRoutesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/navigator.inference.v1.Inference/ListInferenceRoutes",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "navigator.inference.v1.Inference",
                        "ListInferenceRoutes",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod inference_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with InferenceServer.
    #[async_trait]
    pub trait Inference: std::marker::Send + std::marker::Sync + 'static {
        /// Send a completion request routed by the server's inference router.
        async fn completion(
            &self,
            request: tonic::Request<super::CompletionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CompletionResponse>,
            tonic::Status,
        >;
        /// Create a new inference route.
        async fn create_inference_route(
            &self,
            request: tonic::Request<super::CreateInferenceRouteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InferenceRouteResponse>,
            tonic::Status,
        >;
        /// Update an existing inference route.
        async fn update_inference_route(
            &self,
            request: tonic::Request<super::UpdateInferenceRouteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InferenceRouteResponse>,
            tonic::Status,
        >;
        /// Delete an inference route.
        async fn delete_inference_route(
            &self,
            request: tonic::Request<super::DeleteInferenceRouteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteInferenceRouteResponse>,
            tonic::Status,
        >;
        /// List inference routes.
        async fn list_inference_routes(
            &self,
            request: tonic::Request<super::ListInferenceRoutesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListInferenceRoutesResponse>,
            tonic::Status,
        >;
    }
    /// Inference service provides LLM completion capabilities.
    #[derive(Debug)]
    pub struct InferenceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> InferenceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for InferenceServer<T>
    where
        T: Inference,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/navigator.inference.v1.Inference/Completion" => {
                    #[allow(non_camel_case_types)]
                    struct CompletionSvc<T: Inference>(pub Arc<T>);
                    impl<
                        T: Inference,
                    > tonic::server::UnaryService<super::CompletionRequest>
                    for CompletionSvc<T> {
                        type Response = super::CompletionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CompletionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Inference>::completion(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CompletionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/navigator.inference.v1.Inference/CreateInferenceRoute" => {
                    #[allow(non_camel_case_types)]
                    struct CreateInferenceRouteSvc<T: Inference>(pub Arc<T>);
                    impl<
                        T: Inference,
                    > tonic::server::UnaryService<super::CreateInferenceRouteRequest>
                    for CreateInferenceRouteSvc<T> {
                        type Response = super::InferenceRouteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateInferenceRouteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Inference>::create_inference_route(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateInferenceRouteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/navigator.inference.v1.Inference/UpdateInferenceRoute" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateInferenceRouteSvc<T: Inference>(pub Arc<T>);
                    impl<
                        T: Inference,
                    > tonic::server::UnaryService<super::UpdateInferenceRouteRequest>
                    for UpdateInferenceRouteSvc<T> {
                        type Response = super::InferenceRouteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateInferenceRouteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Inference>::update_inference_route(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateInferenceRouteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/navigator.inference.v1.Inference/DeleteInferenceRoute" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteInferenceRouteSvc<T: Inference>(pub Arc<T>);
                    impl<
                        T: Inference,
                    > tonic::server::UnaryService<super::DeleteInferenceRouteRequest>
                    for DeleteInferenceRouteSvc<T> {
                        type Response = super::DeleteInferenceRouteResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteInferenceRouteRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Inference>::delete_inference_route(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteInferenceRouteSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/navigator.inference.v1.Inference/ListInferenceRoutes" => {
                    #[allow(non_camel_case_types)]
                    struct ListInferenceRoutesSvc<T: Inference>(pub Arc<T>);
                    impl<
                        T: Inference,
                    > tonic::server::UnaryService<super::ListInferenceRoutesRequest>
                    for ListInferenceRoutesSvc<T> {
                        type Response = super::ListInferenceRoutesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListInferenceRoutesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Inference>::list_inference_routes(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListInferenceRoutesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for InferenceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "navigator.inference.v1.Inference";
    impl<T> tonic::server::NamedService for InferenceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
